### ISSUE TITLE
性能测试对比

### ISSUE THREAD

**Issue by hcymysql** [Tencent/TenDBCluster-TSpider#1]
我看了您的压力测试报告，没有和官方MariaDB Spider的压测对比。

另外，和直连DB，性能差多少？

**Comment by willhan123** [comment]
和maridb 官方对比：
1. 在后端挂一个分片情况下， 目前约提升30%左右分发性能。
2. 另外，mariadb官方的spider在分片数增多性能会急剧下降（在1024分片下下降90%）；tspider解决了这个问题，且将这个patch提交给mariadb。（mariadb 10.4以后的版本应该合了这个patch)

和直连相比，如果是全cache数据，把转发的压力打满， qps 大约会差5%。
