### ISSUE TITLE
Spider节点和DB节点数据不一致的处理方式

### ISSUE THREAD

**Issue by xoyolovesgame** [Tencent/TenDBCluster-TSpider#13]
通过TSpider操作建库建表过程中服务器异常崩溃了，恢复服务后发现上次操作的库在spider节点和db节点产生了不一致
![image](https://user-images.githubusercontent.com/53810101/104988722-c3e0b100-5a53-11eb-9eda-affa75741ce2.png)
![image](https://user-images.githubusercontent.com/53810101/104988712-bf1bfd00-5a53-11eb-91bb-00bb71e6c02c.png)
无法直接清除该库
![image](https://user-images.githubusercontent.com/53810101/104988733-cc38ec00-5a53-11eb-9e0b-fc34cda39331.png)
尝试修改TSpider节点全局变量ddl_execute_by_ctl=OFF后再次操作提示
![image](https://user-images.githubusercontent.com/53810101/104988743-d1963680-5a53-11eb-824f-2638a7c9ee18.png)
请问这种情况一般是如何产生的/可以通过什么方式处理

**Comment by willhan123** [comment]
1. 想了解下前面的异常崩溃是如何导致的
2. 通常删除库可以用drop database if exists xx的方式来进行

error 1通常是权限问题， 是否装数据库的用户，和当前用户不一致呢？

**Comment by xoyolovesgame** [comment]
> 1. 想了解下前面的异常崩溃是如何导致的
> 2. 通常删除库可以用drop database if exists xx的方式来进行
> 
> error 1通常是权限问题， 是否装数据库的用户，和当前用户不一致呢？

1.是在用sysbench做性能测试，准备数据过程中，机器挂了
2.还是提示权限问题
是用docker部署的，用户应该是一致的

**Comment by willhan123** [comment]
1. 机器挂，是指硬件挂了，还是说数据库有异常。 如果是数据库异常，有日志么
2. 这个数stresstest下的文件截图看一下， 另外如果重装建表能否正常呢
3. 如果初次使用，可以用如下文档试用下
https://tendbcluster.com/book-cn/Documentation/op-guide/docker-compose-tendbcluster.html

**Comment by xoyolovesgame** [comment]
> 1. 机器挂，是指硬件挂了，还是说数据库有异常。 如果是数据库异常，有日志么
> 2. 这个数stresstest下的文件截图看一下， 另外如果重装建表能否正常呢
> 3. 如果初次使用，可以用如下文档试用下
>    https://tendbcluster.com/book-cn/Documentation/op-guide/docker-compose-tendbcluster.html

1. 硬件挂了
2. spider节点是这样的
![image](https://user-images.githubusercontent.com/53810101/105119813-082f8800-5b0c-11eb-93ec-accf29561ebc.png)
现在除了这个库删不掉也不能建表之外其他库操作都正常，也能建新库
3.就是用这个装的

**Comment by willhan123** [comment]
应该还是这个库里的文件权限问题
1. 可以尝试一个表，一个表的drop；可以确定是哪个表异常。  你图里的文件属性看起来有点问题
2. 如果要需要drop这个库， 还有个办法：先把库下面的.frm .par文件物理删掉， 再进行drop database操作
