### ISSUE TITLE
Query crossing shards with limit clause leads to a little high latency response

### ISSUE THREAD

**Issue by seanlook** [Tencent/TenDBCluster-TSpider#16]
```
query1: 
select * from tb_test where field1 = xxx limit 1;
1 row in set (0.034 sec)

query2:
select * from tb_test where field1 = xxx order by id limit 1;
1 row in set (0.005 sec)
```
This is a known issue. Tspider try to optimize the query1 by accessing the shards sequentially, because the rows retrived may be satisfied from the first shard, there is no need to request all backend shards to retrived rows in parallel.

But the bad case is that the only one satisfied row is located in the last shard. Thus this may take `shard_num * one_response_time` to finish the query.

**Comment by willhan123** [comment]
tspider对跨分区查询，通常是将请求并行分发到各存储shard执行，然后在tspider层汇总结果。 tspider上该sql执行时间，取决于各存储shard中执行请求最慢的那个。

但对带limit的跨分片查询，并没有走并行逻辑，是串行依次从各个shard获取结果。 因此tspider上该sql执行时间主要取决于在第几个存储shard命中了满足条件的记录。（上述的sql刚好最后一个分片第12个shard才命中）

为什么上述limit没有走并行 ?
通常情况下，limit是会命中大量结果然后取其中n行，较大概率在较前面的分片即可命中查询请求从而返回结果。  因此串行执行，并不会明显较并行慢； 更主要的好处是，避免tspider侧的流量放大（比如并行limit 100，需要返回100 * shard_num的记录，流量放大 shard_num倍）。
综合考虑，如上述的limit n走了串行执行。

是不是limit n一定串行 ？
上述limit n不并行，是因为该sql有可能在较前面的shard直接命中返回，不需要并行。 
但如果上述sql调整为 order by shard_id limit 1， 因为涉及到排序，则tspider必须分发query到全部的存储shard，汇总结果排序。既然不可避免需要到全部shard请求结果，因此该query是并行执行。

**Comment by willhan123** [comment]
在下个版本中，会增加一个选项，让用户来选择limit是否执行并行

**Comment by willhan123** [comment]
https://github.com/Tencent/TenDBCluster-TSpider/commit/1d51dcf91a5e991ac37757a6a239550622924fe5
done 
增加 全局参数spider_parallel_limit，可控制select + limit是否触发并行。
