### ISSUE TITLE
取模扩容问题

### ISSUE THREAD

**Issue by hcymysql** [Tencent/TenDBCluster-TSpider#2]
比如原来HASH UID取模是64，现在变更256，TSPIDER是如何迁移数据的？可以像MongoDB那样自动迁移数据吗？

**Comment by willhan123** [comment]
目前不支持自动迁移数据；

通常是初期把分片定确定好，不建议变更分片数。 
如果非要变更分数数，要么是停机重导数据；如果不停机，只能通过用tspider作data node热备的方式来同步

**Comment by hcymysql** [comment]
谢谢。
