### ISSUE TITLE
ddl 不支持空间类型 GEOMETRY

### ISSUE THREAD

**Issue by Livenux** [Tencent/TenDBCluster-TSpider#3]
建表的时候不支持 GEOMETRY，是否有其他方法解决？

**Comment by willhan123** [comment]
spider引擎暂不支持GEOMETRY类型。可否用json类型替换GEOMETRY呢 ？

如果对GEOMETRY强需求多的话，我们可以规划进行支持。  有兴趣一起协同开发更好。
